debug: false

logging: 
  level: 
    com: 
      webapp:
        cybersecurityforum:
          controller: DEBUG
captcha:
  alphabet: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
  length:
    min: 6
    max: 8
spring:
  profiles: 
    active: DEV
  thymeleaf: 
    cache: false
  datasource:
    url: jdbc:postgresql://127.0.0.1/app_db
    username: postgres
    password: qwerty
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    transport:
      protocol: smtps
    port: 465
    smtp:
      auth: true
      starttls:
        enable: true
    default-encoding: UTF-8
    debug: false
    